env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - unused-imports
  - import
rules:
  react/prop-types: off
  quotes:
    - error
    - single
  semi:
    - error
    - always
  # organize imports
  import/order:
    - error
    - newlines-between: never
      alphabetize:
        order: asc
        caseInsensitive: true
  # no unused imports
  no-unused-vars: off
  unused-imports/no-unused-imports: error
  unused-imports/no-unused-vars: warn
